version: '3'

services:
  reverse-proxy:
    image: traefik # The official Traefik docker image
    command: --api --docker # Enables the web UI and tells Traefik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock #So that Traefik can listen to the Docker events

  api:
    build: api
    volumes:
      - ./api:/code
    depends_on:
      - "db"
    labels:
      - "traefik.frontend.rule=PathPrefixStrip:/api"
      - "traefik.port=5000"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example

  redis:
    image: redis

  adminer:
    image: adminer
    restart: always
    labels:
      #- "traefik.frontend.rule=Host:adminer.localhost"
      - "traefik.frontend.rule=PathPrefixStrip:/adminer"
      - "traefik.port=8080"